name: learn-github-actions
on: [push]
jobs:
  Job 1:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - run: echo Hello World
        name: Run echo command
      - run: find .
        name: List files


